services:
  db:
    image: postgres:14-alpine
    container_name: auth-app-db-psql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: quizzes_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d quizzes_db" ]
      interval: 5s
      timeout: 5s
      retries: 3
    profiles: [ development ]

    migrate:
      image: migrate/migrate
      command: [
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/message_server_db?sslmode=disable",
        "-path",
        "/migrations",
        "up" ]
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./server/migrations:/migrations
      networks:
        - default
      profiles: [ development ]